apiVersion: v1
kind: Service
metadata:
  name: {{ metadata.name }}
  namespace: {{ metadata.namespace }}
  labels:
    app: {{ metadata.name }}
    thirdparty: Web
spec:
  ports:
  - name: http
    port: 2368
    protocol: TCP
    targetPort: http
  selector:
    app: {{ metadata.name }}
    thirdparty: ghost
